[package]
name = "packetkit"
version = "0.1.0"
edition = "2018"

[lib]
doc = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
anyhow = "1"
num_cpus = "1.6"
pcap-sys = "0.1.3"
pktparse = { version = "0.5", features = ["serde"] }
nom = "6"
dns-parser = "0.8"
tls-parser = "0.10"
dhcp4r = "0.2.0"
ansi_term = "0.12"
reduce = "0.1.1"
atty = "0.2"
env_logger = "0.8"
log = "0.4"
toml = "0.5"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
users = "0.11"
nix = "0.20"
sha2 = "0.9"
dirs-next = "2.0"
base64 = "0.13"
libc = "0.2"

[target.'cfg(target_os="linux")'.dependencies]
syscallz = "0.15"
#syscallz = { path="../syscallz-rs" }

[dev-dependencies]
boxxy = "0.11"